# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1595ef6904ac079c23659f3119bcab1d8dd2f7d4fbfda556a6834827929401ab62797bada789d9b80322e850d3a68cd97c6d5ba94313af1d768cfec9d0fcc97c

test:
  secret_key_base: 2e338831486fc018a61f6d12fdc27094e2e44d06a2631f0369e8d69e1352181e230e3cad9683d402f27995f1ad44464c39a5cd0907c9e85fb30cb7cbc21dd3e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
